version: '3'
services:
  dev-simple-storage:
    container_name: dev-simple-storage
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    env_file: .env
    volumes:
      - ./files:/app/files
      - ./jest.config.js:/app/jest.config.js
      - ./nodemon.json:/app/nodemon.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tslint.json:/app/tslint.json
      - ./src:/app/src
      - ./tests:/app/tests
      - ./node_modules/:/app/node_modules/
    command: npm run start:dev

  simple-storage:
    container_name: simple-storage
    build: 
      context: .
      dockerfile: Dockerfile.production
    tty: true
    env_file: .env.production
    volumes:
      - ./files:/app/files
