FROM node:18-alpine3.15

WORKDIR /app

COPY package*.json ./
COPY [ "tsconfig.json",".env.production", "./"]
COPY src ./src

RUN npm install
ENV NODE_ENV production
RUN npm run build
RUN ln -s /app/dist/cli.js /usr/local/bin/cli
RUN chmod ugo+x /usr/local/bin/cli